// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGxVOPtRcWmwKswg5OY5GmBzae_PZ42ao',
    appId: '1:189058218770:web:dc871a0a86365fad1611cb',
    messagingSenderId: '189058218770',
    projectId: 'gala-application',
    authDomain: 'gala-application.firebaseapp.com',
    storageBucket: 'gala-application.appspot.com',
    measurementId: 'G-Y0BE3K0ZJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidM5cfohXRcs7YEFbyhCka4Ykh4ETYZ4',
    appId: '1:189058218770:android:68b0ab5b9c1c68321611cb',
    messagingSenderId: '189058218770',
    projectId: 'gala-application',
    storageBucket: 'gala-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxvCbDqq1Ah6dNAR7wGzhe5jJiS4Io2WY',
    appId: '1:189058218770:ios:16ab3f5a64869d041611cb',
    messagingSenderId: '189058218770',
    projectId: 'gala-application',
    storageBucket: 'gala-application.firebasestorage.app',
    iosBundleId: 'com.parents.lakshyaschoolbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxvCbDqq1Ah6dNAR7wGzhe5jJiS4Io2WY',
    appId: '1:189058218770:ios:2932621a870091021611cb',
    messagingSenderId: '189058218770',
    projectId: 'gala-application',
    storageBucket: 'gala-application.appspot.com',
    iosBundleId: 'com.example.galaTravelsApp.RunnerTests',
  );
}